name: YASIYA MDX Bot Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # har 6 ghante auto run

concurrency:
  group: prince-mdxi-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Pull Latest Update
        run: |
          git pull origin main || true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install PM2
        run: npm install -g pm2

      - name: Install Modules
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
      - name: Start Bot
        run: |
          echo "Bot started at $(date)"
          pm2 start npm --name prince-mdxi -- start
      - name: Auto Restart Bot
        run: |
          pm2 restart prince-mdxi || pm2 start npm --name prince-mdxi -- start
      - name: Show Logs
        run: pm2 logs prince-mdxi --lines 100
        
